application: jist-in
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "2h"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: never

- url: /.*/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)
  secure: never

- url: /.*/(.*\.js)
  static_files: js/\1
  upload: js/(.*\.js)
  secure: never

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  secure: never

- url: /robots.txt
  script: robots.app
  secure: never

- url: /.*
  static_files: jist.html
  upload: jist.html
  secure: never
